service:
  spec:
    externalTrafficPolicy: Local
logs:
  access:
    enabled: true
    fields:
      general:
        defaultmode: keep
        names:
          StartUTC: drop
env:
- name: TZ
  value: Europe/Paris
