apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: gitapps
  namespace: fleet-local
spec:
  branch: main
  repo: https://github.com/anypot/gitapps
  paths:
  - csi-driver-smb
  - sealed-secrets
  - misc
